### ISSUE TITLE
Installation Error (Windows)

### ISSUE THREAD

**Issue by achapkowski** [pythongssapi/requests-gssapi#14]
Hello,

When I install the package, I get the following error:

```
 Complete output from command python setup.py egg_info:
    'krb5-config' is not recognized as an internal or external command,
    operable program or batch file.
    In distributed package, building from C files...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\andr5624\AppData\Local\Temp\pip-install-nb6g9mu7\gssapi\setup.py", line 58, in <module>
        link_args = get_output('krb5-config --libs gssapi')
      File "C:\Users\andr5624\AppData\Local\Temp\pip-install-nb6g9mu7\gssapi\setup.py", line 38, in _get_output
        res = subprocess.check_output(*args, shell=True, **kwargs)
      File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\spnego\lib\subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\spnego\lib\subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 1.
```

**Comment by frozencemetery** [comment]
Yes, you need a GSSAPI installation to use python-gssapi.  Available providers are [MIT Kerberos](http://web.mit.edu/kerberos/) and [Heimdal](http://h5l.org/).

The failure is expected - something needs to provide krb5-config, else we can't link.

**Comment by achapkowski** [comment]
@frozencemetery oh ok, is that documented anywhere?

**Comment by frozencemetery** [comment]
https://github.com/pythongssapi/python-gssapi/#basic

**Comment by holmes-py** [comment]
Got here since I was trying to find a solution for similar problem with krb5-config becoming a problem in installation of GSSAPI. 
One potential solution is installing both `krb5-config libkrb5-dev` (for Ubuntu/Debian)   
  
Though this is probably not a proper fix and only a hot patch to make the thing work, you can follow the discussion here:
https://www.mail-archive.com/pgadmin-support@lists.postgresql.org/msg03658.html

**Comment by jborean93** [comment]
I’m not sure what you mean, you need those packages as they contain the headers and gssapi C API that this library wraps.

**Comment by gmfcd128** [comment]
There's no krb5-config command after I install kfw-4.1-amd64.msi , does anyone know what i missed?
