### ISSUE TITLE
Implement multilegged auth draft

### ISSUE THREAD

**Issue by frozencemetery** [pythongssapi/requests-gssapi#2]
There's a proposed HTTP extension for supporting SPNEGO auth with more than one round trip in HTTPS: https://github.com/MikeBishop/http-misc-extensions/blob/master/draft-montenegro-httpauth-multilegged-auth.md

We should think about implementing this.,

**Comment by michael-o** [comment]
This one has been moved to obsolete: https://github.com/MikeBishop/http-misc-extensions/blob/master/obsolete/draft-montenegro-httpauth-multilegged-auth.md
