### ISSUE TITLE
Explicit Principal code sample is wrong

### ISSUE THREAD

**Issue by michael-o** [pythongssapi/requests-gssapi#33]
The sample says:
```
name = gssapi.Name("user@REALM", gssapi.NameType.hostbased_service)
creds = gssapi.Credentials(name=name, usage="initiate")
```
but the provided principal is not a hostbased service eligible for initiate.

**Comment by frozencemetery** [comment]
Hi, if you'd like this fixed sooner, feel free to submit a pull request :)  Otherwise I'll get to it when I have a bit more time to look.

**Comment by michael-o** [comment]
> 
> 
> Hi, if you'd like this fixed sooner, feel free to submit a pull request :) Otherwise I'll get to it when I have a bit more time to look.

I happily will, I just wanted to clarify first.
