### ISSUE TITLE
Tags and Pypi

### ISSUE THREAD

**Issue by erinn** [pythongssapi/requests-gssapi#5]
Folks could I kindly request that you tag your releases so people like me have a fighting (read easier) chance to bundle this module as an RPM? Could you also push the release to pypi to make installation easier?
Thanks.

**Comment by frozencemetery** [comment]
Don't worry, I plan to :)  There hasn't been a release yet (blocking on #3), but there should be very soon.  This is a relatively new project and I'm glad you're interested!

**Comment by erinn** [comment]
Ah ok, had been confused by the release numbers ;). I had been using requests-negotiate on a new project, but it doesn't expose all that this one does: https://github.com/ox-it/requests-negotiate But I found this via a talk posted online to the MIT computer club: https://mivehind.net/2017/11/06/kerberos-underworld/ 

Anyway, great to see this, look forward to a release.

**Comment by frozencemetery** [comment]
Hmm, I didn't think I mentioned requests-gssapi in that talk?  I did talk about [python-gssapi itself](https://github.com/pythongssapi/python-gssapi), which requests-gssapi consumes, there though.

**Comment by erinn** [comment]
You didn't, you mentioned the test suite, and gssapi console which I freaking love, but that got me to this github group and then I found this. I'm writing a client and server for a (very simple) PKI, we have kerb deployed everywhere, so I want to leverage that, but though this isn't like the dark old days of kerb, support is still a bit spotty. So really glad to see this project and some life put into python kerberos support.

**Comment by DirectXMan12** [comment]
> gssapi console which I freaking love

❤️ glad to hear you like it. 

@frozencemetery you should be able to copy the test-infra and build-infra from python-gssapi proper
