### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by joakim-tjernlund** [pythongssapi/requests-gssapi#51]
Been 3 years since last

**Comment by jborean93** [comment]
Thanks for the reminder, I'll try and push a new release today.

**Comment by jborean93** [comment]
[requests-gssapi v1.3.0](https://pypi.org/project/requests-gssapi/1.3.0/) has been released on PyPI now.

**Comment by joakim-tjernlund** [comment]
Downloading 'https://github.com/pythongssapi/requests-gssapi/releases/download/v1.3.0/requests-gssapi-1.3.0.tar.gz'
--2024-02-16 08:37:08--  https://github.com/pythongssapi/requests-gssapi/releases/download/v1.3.0/requests-gssapi-1.3.0.tar.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-02-16 08:37:08 ERROR 404: Not Found.


Seems to be missing in the download area

**Comment by jborean93** [comment]
It is on PyPI like all other releases.
